# Default configuration file

test: test
LOGGING_LEVEL: INFO

POSTGRESQL_URI: postgresql://user:pass@localhost:5432/test

# Proxy server
START_PROXY_SERVER: TRUE
COUNT_PROXY_SERVERS: 1 #  -1 auto

PARSE_SOURCES:
  - 'Sslproxies24_top'
